// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoTranslateGtk {
    
    
    public partial class AppWindow {
        
        private Gtk.Action Help;
        
        private Gtk.Action miAbout;
        
        private Gtk.Action tbtnTranslate;
        
        private Gtk.Action close;
        
        private Gtk.Action miApplication;
        
        private Gtk.Action Close;
        
        private Gtk.Action OnlineUserGuide;
        
        private Gtk.VPaned vpaned1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar21;
        
        private Gtk.Toolbar toolbar1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label2;
        
        private Gtk.ComboBoxEntry cmbTranslators;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label4;
        
        private Gtk.ComboBoxEntry cmbLanguages;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.TextView txtOriginalText;
        
        private Gtk.Label GtkLabel3;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.TextView txtTranslatedText;
        
        private Gtk.Label GtkLabel4;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget MonoTranslateGtk.AppWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.Help = new Gtk.Action("Help", Mono.Unix.Catalog.GetString("Help"), null, null);
            this.Help.ShortLabel = Mono.Unix.Catalog.GetString("Help");
            w2.Add(this.Help, null);
            this.miAbout = new Gtk.Action("miAbout", Mono.Unix.Catalog.GetString("About"), null, "gnome-stock-about");
            this.miAbout.ShortLabel = Mono.Unix.Catalog.GetString("About");
            w2.Add(this.miAbout, null);
            this.tbtnTranslate = new Gtk.Action("tbtnTranslate", Mono.Unix.Catalog.GetString("Translate!"), null, "gtk-apply");
            this.tbtnTranslate.ShortLabel = Mono.Unix.Catalog.GetString("Translate!");
            w2.Add(this.tbtnTranslate, null);
            this.close = new Gtk.Action("close", null, null, "gtk-close");
            w2.Add(this.close, null);
            this.miApplication = new Gtk.Action("miApplication", Mono.Unix.Catalog.GetString("Application"), null, null);
            this.miApplication.ShortLabel = Mono.Unix.Catalog.GetString("Application");
            w2.Add(this.miApplication, null);
            this.Close = new Gtk.Action("Close", Mono.Unix.Catalog.GetString("_Close"), null, "gtk-close");
            this.Close.ShortLabel = Mono.Unix.Catalog.GetString("_Close");
            w2.Add(this.Close, null);
            this.OnlineUserGuide = new Gtk.Action("OnlineUserGuide", Mono.Unix.Catalog.GetString("Online User Guide"), null, "gtk-help");
            this.OnlineUserGuide.ShortLabel = Mono.Unix.Catalog.GetString("Online User Guide");
            w2.Add(this.OnlineUserGuide, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "MonoTranslateGtk.AppWindow";
            this.Title = Mono.Unix.Catalog.GetString("Mono Translate");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child MonoTranslateGtk.AppWindow.Gtk.Container+ContainerChild
            this.vpaned1 = new Gtk.VPaned();
            this.vpaned1.CanFocus = true;
            this.vpaned1.Name = "vpaned1";
            this.vpaned1.Position = 172;
            // Container child vpaned1.Gtk.Paned+PanedChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar21'><menu action='miApplication'><menuitem action='Close'/></menu><menu action='Help'><menuitem action='OnlineUserGuide'/><menuitem action='miAbout'/></menu></menubar></ui>");
            this.menubar21 = ((Gtk.MenuBar)(w1.GetWidget("/menubar21")));
            this.menubar21.Name = "menubar21";
            this.vbox1.Add(this.menubar21);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar21]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem action='close'/><separator/><toolitem action='tbtnTranslate'/></toolbar></ui>");
            this.toolbar1 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar1")));
            this.toolbar1.Name = "toolbar1";
            this.toolbar1.ShowArrow = false;
            this.vbox1.Add(this.toolbar1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            // Container child hbox2.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Translator:");
            this.hbox2.Add(this.label2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.label2]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.cmbTranslators = Gtk.ComboBoxEntry.NewText();
            Gtk.Tooltips w6 = new Gtk.Tooltips();
            w6.SetTip(this.cmbTranslators, "Select the Translator Provider", "Select the Translator Provider");
            this.cmbTranslators.CanFocus = true;
            this.cmbTranslators.Name = "cmbTranslators";
            this.hbox2.Add(this.cmbTranslators);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.cmbTranslators]));
            w7.Position = 1;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w8.Position = 2;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            // Container child hbox3.Gtk.Box+BoxChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Languaje");
            this.hbox3.Add(this.label4);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox3[this.label4]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.cmbLanguages = Gtk.ComboBoxEntry.NewText();
            w6.SetTip(this.cmbLanguages, "Language", "Language");
            this.cmbLanguages.CanFocus = true;
            this.cmbLanguages.Name = "cmbLanguages";
            this.hbox3.Add(this.cmbLanguages);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox3[this.cmbLanguages]));
            w10.Position = 1;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w11.Position = 3;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            this.frame1.LabelXalign = 0F;
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.txtOriginalText = new Gtk.TextView();
            this.txtOriginalText.CanFocus = true;
            this.txtOriginalText.Name = "txtOriginalText";
            this.GtkAlignment.Add(this.txtOriginalText);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("<b>Original Text</b>");
            this.GtkLabel3.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel3;
            this.vbox1.Add(this.frame1);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
            w14.Position = 4;
            this.vpaned1.Add(this.vbox1);
            Gtk.Paned.PanedChild w15 = ((Gtk.Paned.PanedChild)(this.vpaned1[this.vbox1]));
            w15.Resize = false;
            // Container child vpaned1.Gtk.Paned+PanedChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            this.frame2.LabelXalign = 0F;
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.txtTranslatedText = new Gtk.TextView();
            this.txtTranslatedText.CanFocus = true;
            this.txtTranslatedText.Name = "txtTranslatedText";
            this.txtTranslatedText.Editable = false;
            this.GtkAlignment1.Add(this.txtTranslatedText);
            this.frame2.Add(this.GtkAlignment1);
            this.GtkLabel4 = new Gtk.Label();
            this.GtkLabel4.Name = "GtkLabel4";
            this.GtkLabel4.LabelProp = Mono.Unix.Catalog.GetString("<b>Translated Text</b>");
            this.GtkLabel4.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel4;
            this.vpaned1.Add(this.frame2);
            this.Add(this.vpaned1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.miAbout.Activated += new System.EventHandler(this.OnAboutActivated);
            this.tbtnTranslate.Activated += new System.EventHandler(this.OnTbtnTranslateActivated);
            this.close.Activated += new System.EventHandler(this.action_CloseApp);
            this.Close.Activated += new System.EventHandler(this.action_CloseApp);
            this.OnlineUserGuide.Activated += new System.EventHandler(this.OnOnlineUserGuideActivated);
            this.cmbTranslators.Changed += new System.EventHandler(this.OnCmbTranslatorsChanged);
        }
    }
}
